baseURL: https://leonie.fun
languageCode: fr-FR
defaultContentLanguage: en
title: Site internet de Léonie Fun
theme: cupper-hugo-theme
disqusShortname: yourdiscussshortname
enableGitInfo: true

imaging:
  quality: 99

menu:
  nav:
    - name: Bonjour
      url: /
      weight: 1
    - name: Interventions
      url: /interventions/
      weight: 2
    - name: Formes
      url: /dessins/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
